### ISSUE TITLE
Ne deluje

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#1]
_Zaenkrat_ še ni **nič** narejeno!!!!

``` R
x<-1+1
y<-x*42
```

(naredi desni alt in navednice)

**Comment by jaanos** [comment]
Svetujem ti, da tale issue zapreš, in nasploh sproti zapiraš issueje, ki jih razrešiš. Tako bo lažje slediti problemom, ki se bodo sproti pojavljali.
