### ISSUE TITLE
Besedilo

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#10]
Zakaj mi besedilo sredinsko poravna? 
Rad bi da bi mi besedilo v project.Rmd poravnalo na levo.

**Comment by jaanos** [comment]
Problem sta besedili pri grafih `graf6` in `graf7`, ki vsebujeta znak `%`. Tu gre za očitno za hrošča v knitru, ki se mu lahko izogneš tako, da pred `%` postaviš še `\\`, npr.

``````
```{r graf6, echo=FALSE, warning=FALSE, fig.cap='Drzave z dolgom vecjim od 100\\% BDP leta 2006', fig.align='center'}
``````

Potem bo besedilo pod grafoma pravilno prikazano, preostalo besedilo pa bo pravilno poravnano.
