### ISSUE TITLE
Shinny

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#13]
Kaj sem naredil narobe pri shinny, začne mi odpirati server, vendar mi potem napiše, da je prišlo do napake. Hotel sem narisati grafa 'prvi_graf' in 'enajsti_graf' in tabelo 'napoved.tabela', vendar mi jih noče odpreti v shinny, kaj naj naredim?

**Comment by jaanos** [comment]
Trenutno v `server.r` in `ui.r` kličeš neobstoječa programa `podatki/podatki.r` in `uvoz/uvoz.r`. Svetujem, da vse ukaze `source` premakneš v program `shiny.r`, tega pa v vrhnjo mapo projekta (torej ven iz mape `shiny/`). `shiny.r` lahko potem uporabiš za klicanje Shinyja - tako se bo tvoj program izvedel samo enkrat (ko boš vključil Shiny v poročilo, bodo vsi `source` prav tako že opravljeni in se ne bodo ponovno klicali).

Sicer pa trenutno nimaš strežniškega dela aplikacije. Tam namreč definiraš elemente (ti so lahko seveda odvisni od vhoda), ki jih potem v `ui.r` izrisuješ. Poglej si v vzorec, kako je to tam narejeno.

**Comment by aleksandrov2** [comment]
Pozdravljeni,

v projekt.rmd v vrstici 202 sem vključil shinny, da lahko sam izberem leto, ki se bo prikazalo na grafu To mi sicer naredi, vendar je graf zelo izrojen, slabih dimenzij in nepregleden. Kako naj naredim, da bo v pravilnem merilu cel čas in da bo pregleden?

**Comment by jaanos** [comment]
Pri meni graf lepo izgleda. Ali lahko pripneš sliko, da vidim, kako izgleda? (Lahko pripneš kar v issue.) Je kaj drugače, če poročilo odpreš v brskalniku (gumb _Open in Browser_ levo zgoraj)?

**Comment by aleksandrov2** [comment]
1.) Mislim ni mi všeč, da se graf tako spreminja, ko spreminjam leta. Kaj naj naredim, dabo skala fiksirana, torej da bo deficit za vsako leto tekel od 5% do -15% in da bo zadolženost vedno fiksirana na skali od 0 do 190%?
Tudi pri drugih dveh sliderjih v shiny, kjer sem dodal možnost gledanja dolga in deficita bi rad fiksiral skalo. Imam tudi problem, da se je graf tako pomanjšal, da se zelo slabo vidi imena držav.

2.) Plus rad bi dodal še to, da ko spreminjaš leta, se ne bi spreminjal sam graf, ampak tudi tabela, ki bo kazala predikcijo o deficitu. Zaenkrat mi tabela ne dela, kaj je narobe? (v projektu.rmd vrstica 220)

3.) Če boste odprli projekt.rmd, boste videli da sem dodal 3 grafe s sliderjem, kjer se da spreminjati leta (od 2006 do 2014). Prvi graf kaže zadolženost držav, drugi deficite in zadnji naj bi kazal dolg in deficit vseh držav hkrati in predikcijo + tabela. Zakaj mi samo prvi graf s sliderjem dela, medtem ko drugi in tretji in tabela ne delajo?

**Comment by aleksandrov2** [comment]
1.) Mislim ni mi všeč, da se graf tako spreminja, ko spreminjam leta. Kaj naj naredim, dabo skala fiksirana, torej da bo deficit za vsako leto tekel od 5% do -15% in da bo zadolženost vedno fiksirana na skali od 0 do 190%?
Tudi pri drugih dveh sliderjih v shiny, kjer sem dodal možnost gledanja dolga in deficita bi rad fiksiral skalo. Imam tudi problem, da se je graf tako pomanjšal, da se zelo slabo vidi imena držav.

2.) Plus rad bi dodal še to, da ko spreminjaš leta, se ne bi spreminjal sam graf, ampak tudi tabela, ki bo kazala predikcijo o deficitu. Zaenkrat mi tabela ne dela, kaj je narobe? (v projektu.rmd vrstica 220)

3.) Če boste odprli projekt.rmd, boste videli da sem dodal 3 grafe s sliderjem, kjer se da spreminjati leta (od 2006 do 2014). Prvi graf kaže zadolženost držav, drugi deficite in zadnji naj bi kazal dolg in deficit vseh držav hkrati in predikcijo + tabela. Zakaj mi samo prvi graf s sliderjem dela, medtem ko drugi in tretji in tabela ne delajo?

**Comment by jaanos** [comment]
- Da fiksiraš osi, grafu prištej funkciji `xlim` in `ylim`. V tvojem primeru želiš torej prišteti `+ xlim(0, 190) + ylim(-15, 5)`. Da bo premica modela prikazana čez celotno širino grafa, k `geom_smooth` dodaj še parameter `fullrange=TRUE`.
- Da bo prikazalo tabelo, dodaj še vrstico `napoved.tabela` na konec bloka znotraj `renderTable` (lahko bi jo tudi vrnil z `return`).
- Da bodo delovali vsi drsniki, vsakemu daj svoje ime (zdaj so vsi trije `"leto"`).

**Comment by aleksandrov2** [comment]
Sem vse to naredil in je še slabše, sedaj mi ničesar noče narisati, ko hočem pognati projekt.rmd.

**Comment by jaanos** [comment]
Popravi še `input$leto` v ustrezna nova imena.
