### ISSUE TITLE
dimenzije zemljevida

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#14]
1.) V projektu.rmd sem v vrstici 200 hotel narediti slider, ki bo spreminjal podatke v zemljevidu od leta 2006 do 2014. Če boste pognali datoteko, boste videli, da mi zemljevid nariše in tudi slider dela, vendar so dimenzije napačne, zemljevid je zelo popačen. Spodaj pod sliderjem sem pustil še stari zemljevid, ki fiksirano kaže podatke iz leta 2014. Kaj naj naredim, da bo zemljevid s sliderjem  v enakem razmerju kot spodnji fiksirani zemljevid. 
Zemljevid s sliderjem se mi namreč trenutno zdi popačen in slabih dimenzij.

2.) Kako naj fiksiram skalo, torej legendo, tisto, ki kaže barve glede na dolg. Rad bi, da bi bila skala svetlo modra pri 0 in temno modra pri 190. Trenutno se skala spreminja glede na leto, ki ga določim in to mi ni všeč

**Comment by jaanos** [comment]
Kar se dimenzij zemljevida tiče, lahko poskusiš ukazu `renderPlot` podati parametra `width` in `height`. Prvotni zemljevid je dimenzij 672x480, tako da lahko poskusiš s temi in se še malo igraš, da dosežeš želen izgled. Vsaj pri meni sta sicer zemljevida še vedno nekoliko različna - Shinyjev zemljevid npr. naredi manjšo legendo in uporabi drugo pisavo.

Skalo fiksiraš tako, da k `scale_fill_continuous` podaš parameter `limits` s skrajnimi točkami, npr. `limits = c(0, 200)`.
