### ISSUE TITLE
leta v grafu

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#15]
V datoteki projekt.rmd sem v vrstici 168 naredil graf, ki prikazuje rast dolgov evropskih držav. Uporabnik lahko s pomočjo funkcije radioButtons določa katero državo bi rad videl. Vse dela, vendar če boste pognali apikacijo, boste videli, da so na x koordinati leta čudno označena. Namesto, da bi pod vsakih stolpcev bilo leto od 2006 do 2014, so prikazana samo tri leta: 2007.5 , 2010.0 in 2012.5. Kaj naj naredim, da bodo leta lepo prikazana, torej pod vsakih stolpcev ustrezno leto.

**Comment by jaanos** [comment]
Če hočeš prisiliti, da se izpišejo vsa leta, iz njih naredi faktor - torej k `aes` podaj parameter `x = factor(Leto)`. Koristno bo potem tudi spremeniti oznako osi x.
