### ISSUE TITLE
PROJEKT

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#16]
1.) Tako naredil sem tudi shinny app, ali je v redu? Bi mi lahko samo vi popravili, da bo vsak graf v svoji vrsti, ne pa da so sedaj vsi natlačeni eden za drugim. Ali pa še bolje, da bo vsak graf pod svojim sliderjem.

2.) Sicer je projekt končan, ali moram kontaktirati profesor Orbaniča ali boste to vi uredili?

**Comment by jaanos** [comment]
Bom dodal povezavo na projekt, s prof. Orbanićem se pa domeni za termin zagovora.

Za poganjanje samostojne aplikacije Shiny poskrbi, da bodo v `shiny.r` pravi ukazi `source`, tako da se jo bo dalo enostavno pognati.

**Comment by jaanos** [comment]
Kar se postavitve v Shinyju tiče, bo morda najbolje, če imaš vsak graf v svojem zavihku, npr.

``` R
library(shiny)
shinyUI(
  ui <- fluidPage(

    titlePanel("Analiza dolga in primankljaja držav v Evropski uniji"),
    tabsetPanel(
      tabPanel("Dolg",
               sliderInput(inputId="leto_1",label="Leto",min=2006,max=2014,value=2007,sep=""),
               plotOutput("dolg")),
      tabPanel("Deficit",
               sliderInput(inputId="leto_2",label="Leto",min=2006,max=2014,value=2007,sep=""),
               plotOutput("deficit"))
      )
    )
  )
```

Javi mi, ko spremeniš, da posodobim povezavo.
