### ISSUE TITLE
ZAKLJUČEK PROJEKTA

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#17]
Tako sem popolnoma zaključil projekt, bi prosil da mi ga posodobite.

Lp

**Comment by jaanos** [comment]
Sem posodobil - vseeno pa v `shiny.r` namesto `podatki/podatki.r` (ki ne obstaja) vključi `vizualizacija/vizualizacija.r`.

**Comment by aleksandrov2** [comment]
Sem popravil

**Comment by jaanos** [comment]
V redu, posodobljeno.
