### ISSUE TITLE
Uvoz in grafi

### ISSUE THREAD

**Issue by jaanos** [aleksandrov2/APPR-2015-16#2]
Kot sem že omenil, pri uvozu datotek CSV navedi še kodiranje znakov (`fileEncoding = "UTF-8"`) - to bi moralo odpraviti problem z odvečnimi znaki pred imenom stolpca `LOCATION`.

Opažam, da grafih uporabljaš parameter `mode = "markers"`, ki pa pri meni ne deluje (sem si namestil zadnjo verzijo ggplot2 in plotly, pa vseeno ne pomaga). Če želiš oznake držav izpisati navpično, lahko grafu prišteješ npr. `theme(axis.text.x = element_text(angle = 90, vjust = 0.5))`.

Poleg tega očitno z novo verzijo ggplot2 ne deluje več parameter `y` pri `geom_hline` - očitno je pravi parameter `yintercept`.

Da se ti v poročilu ne bo izpisalo sporočilo, ki ga izpiše `inner_join`, bloku kode, kjer vključiš `uvoz.r`, dodaj še parameter `message=FALSE` (tako kot pri prvem bloku).

**Comment by aleksandrov2** [comment]
Moj projekt je pripravljen za oddajo, samo nisem zamenjal ukaza `geom_hline` z ukazom `yintercept`, ker imam še staro verzijo Rstudia in mi ukaz `geom_hline` normalno dela. Kako naj zamenjam z ukazom `yintercept` ne vem. 

Lp

**Comment by jaanos** [comment]
Mišljeno je, da namesto `geom_hline(y = vrednost)` pišeš `geom_hline(yintercept = vrednost)`.

**Comment by aleksandrov2** [comment]
Sem zamenjal vse potrebne kode

**Comment by jaanos** [comment]
V redu, bom dodal.
