### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#3]
Ker analiziram zadolženost držav v evroobmočju, bi potreboval samo zemljevid Evrope, vendar sem na  spletnih straneh našel samo možnosti downlouda zemljevida sveta. Kje bi se dalo dobiti zemljevid Evrope?

**Comment by jaanos** [comment]
Za Evropo lahko vzameš kar zemljevid sveta, saj je celina napisana kot stolpec v zemljevidu in tako lahko narišeš samo izbrane države. Ker pa najbrž nočeš risati celotne Rusije in nekaerih ozemelj, ki spadajo pod evropske države (npr. Francoska Gvajana), si lahko pomagaš še s parametroma `xlim` in `ylim`, da omejiš območje risanja.

Potrebno bo tudi nekoliko prirediti funkcijo `pretvori.zemljevid`, da bo pravilno delala na filtriranem zemljevidu, oziroma da bo sama filtrirala. Osnoven zemljevid lahko potem narišeš nekako tako:

``` R
pretvori.zemljevid <- function(zemljevid, pogoj = TRUE) {
  fo <- fortify(zemljevid[pogoj,])
  data <- zemljevid@data
  data$id <- as.character(0:(nrow(data)-1))
  return(inner_join(fo, data, by="id"))
}

svet <- uvozi.zemljevid("http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip",
                        "ne_110m_admin_0_countries")
evropa <- pretvori.zemljevid(svet, svet$continent == "Europe")
ggplot() + geom_polygon(data = evropa, aes(x = long, y = lat, group = group),
                        color = "grey") + xlim(-10, 50) + ylim(34, 72)
```

Funkcijo `pretvori.zemljevid` lahko seveda uporabljaš tako kot prej - za izrisovanje celega sveta ti parametra `pogoj` ni potrebno podati.

**Comment by aleksandrov2** [comment]
Ampak mi napiše, da ne najde funkcije uvozi.zemljevid, čeprav to funkcijo imam v mapi lib, zakaj?

**Comment by jaanos** [comment]
Prej poženi program `lib/libraries.r`, da se ti naložijo ustrezne knjižnice in ta funkcija.

**Comment by aleksandrov2** [comment]
V mapi analiza.r sem naredil zem4, ki prikazuje evropske države razdeljene v 5 skupin. Vsako skupino sem poimenoval in vsaki ročno določil barvo, vendar mi nekaj ne dela, zanima me kje sem se zmotil.

Lp

**Comment by jaanos** [comment]
Trenutno se ti `analiza.r` ustavi v vrstici 38, kjer se nanašaš na neobstoječo spremenljivko `skupina` - verjetno hočeš tam `podatki3.skupine.` V naslednji vrstici imaš podobno - tam ti manjka še `m3`.

Naslednjič se zalomi, ko definiraš spremenljivko `imena` - izgleda, kot da kličeš funkcijo `skupina2`. Ker pa je to razpredelnica, uporabi oglate oklepaje. Poleg tega imaš podatke v stolpcu `skupina`, ne pa `skupina2`, tako da to popravi pri indeksu stolpca. Potem bo zemljevid deloval.
