### ISSUE TITLE
Uvoz html (dodatni podatki)

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#4]
Danes sem se pri izdelavi zemljevida sveta, kjer pa imam podatke samo o Evropi, Japosnki in ZDA , spomnil, da bi rad za konec v bistvu naredil zemljevid vseh držav sveta in pokazal, da so Japonska, ZDA in Evropa res najbolj zadolžene. Podatke sem hotel uvoziti iz:

http://www.tradingeconomics.com/country-list/government-debt-to-gdp

kjer druga tabela prikazuje podatke o zadolženosti vseh državah sveta. V datoteki vizualizacija.r sem takoj na začetku začel pisati, vendar ne vem kako naj poiščem podatke. Pri uvozu podatkov z wikipedije je bilo lahko najti 'table', tukaj pa tega sploh ne najdem.

**Comment by jaanos** [comment]
Tabelo lahko najdeš glede na njen atribut `class`. Ker je več tabel z enako vrednostjo tega atributa, bo treba namesto `html_node` uporabiti `html_nodes`, nato pa vzeti prvo najdeno tabelo:

``` R
tabela2 <- stran2 %>%
  html_nodes(xpath="//table[@class='table table-condensed table-hover']") %>%
  .[[1]] %>% html_table()
```

**Comment by aleksandrov2** [comment]
Ja ampak jaz bi rad imel drugo tabelo in ne prve, ker druga tabela ima vsebovane vse države sveta

**Comment by jaanos** [comment]
Potem zamenjaj `.[[1]]` z `.[[2]]`, pa očitno bo treba pri `html_table` podati še parameter `fill = TRUE`, ker ima glava manj celic kot preostale vrstice.

**Comment by aleksandrov2** [comment]
imam problem, pri uvozu podatkov iz wikipedije, sem direktno dobil tabelo s stolpci Drzava, 2009, 2010, 2011. Sedaj pa dobim tabelo2 in noter imam kar ene stolpce še spredaj in spodaj še ogromno čudnih podatkov, kaj naj naredim, da bi imel samo en stolpec z državami in en stolpec z dolgom?

**Comment by jaanos** [comment]
Če prav razumem, želiš ohraniti prva dva stolpca. Koristno bo seveda, če ju tudi preimenuješ, da lahko potem z njima normalno delaš, npr.

``` R
tabela2 <- tabela2[1:2]
names(tabela2) <- c("Drzava", "Dolg")
```

Pri meni sicer `tabela2` lepo izgleda - na koncu je sicer stolpec `NA`-jev, drugače pa je taka kot na spletni strani. Je pri tebi drugače?
