### ISSUE TITLE
PRILEGANJE PODATKOV

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#5]
Zanima me, zakaj mi ne dela linearna regresija z metodo najmanjših kvadratov, ki sem jo poskusil uporabiti. V mapi vizualizacija.r sem pri grafu deseti_graf dodal še:

deseti_graf + geom_smooth(method = "lm")

vendar mi, ko narišem graf sploh ne pokaže črte, ki bi aproksimirala podatke, zakaj?

**Comment by aleksandrov2** [comment]
Spodaj pod grafom sem naredil predict in ocenil, kakšen bi bil deficit, če bi se dolg povečal na npr. 250% BDP in to mi normalno dela, samo geom_smooth pa noče narisati premice na graf?

**Comment by jaanos** [comment]
Očitno `geom_smooth` ni všeč, da si že uporabil `color` (dejansko je črte risalo v legendo). Šlo bo, če `color` in `size` podaš pri `geom_point`:

``` R
deseti_graf <- ggplot(podatki3 %>% filter(Cas == 2006),
                      aes(x = Dolg, y = Deficit)) + 
  guides(color = guide_legend(ncol = 2)) +
  geom_point(aes(color = Drzava, size = Dolg-10*Deficit)) +
  geom_hline(yintercept=crta) + 
  geom_hline(yintercept=crta1, colour="red") 

deseti_graf + geom_smooth(method = "lm")
```

**Comment by aleksandrov2** [comment]
Super, vprašal bi samo še kakšen je že ukaz, da izgine to sivo območje okrog te premice?

**Comment by jaanos** [comment]
Pri `geom_smooth` dodaj parameter `se = FALSE`.

**Comment by aleksandrov2** [comment]
Hvala
