### ISSUE TITLE
Centroidi

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#6]
Sedaj ko imam zemljevid zadolženosti držav v evropski uniji, bi lahko izbral nekaj centroidov (referenčnih držav) in narisal katere so jim podobne. Sedaj me zanima kaj bi bilo najbolje primerjati, ali naj preprosto naredim npr. 5 skupin in primerjam zadolženost, deficit, oboje? Saj to je poanta teh skupin ane, da grafično pokažemo, katere države so si podobne v določenih karakteristikah? Ali bi se iz tega dalo kaj dolgoročno napovedati?

**Comment by jaanos** [comment]
Če delaš tako razvrščanje, je vsekakor smiselno, da uporabiš več kot samo en podatek (sicer lahko samo primerjaš številke). Seveda bo potem grafični prikaz dobljenih skupin dobrodošel. Če se bo dalo kaj napovedati, pa je seveda odvisno od samih podatkov - en od ciljev projekta je seveda ta, da ugotoviš, na kakšne zakonitosti lahko sklepaš iz svojih podatkov.

**Comment by aleksandrov2** [comment]
Pozdravljeni, imam problem z zemljevidi v mapi analiza.r in sicer zem3 prikazuje evropske države razporejene v 2 skupini, da se grafično vidi zadnje čase tako velikokrat izrečeno besedo polarizacija evrope na sever in jug in zem4 prikazuje razporeditev evrope na 5 različnih skupin držav. Problem je, da mi noče narisati zemljevida zem4 in tudi ko zaženemi project.Rmd mi reče, da sploh ne more narisati zemljevida zem3 in zem4?
Prav tako me zanima kako bi se dalo fiksirati barve, npr pri zem3, da bi severne države bile vedno označene z modro in južne vedno z rdečo, ne pa da je tako kot sedaj, ko je to stvar naključja?
Kako bi se dalo poleg legende kjer je sedaj zraven barve označena samo številka, napisati sever zraven modre in jug zraven rdeče barve?

**Comment by aleksandrov2** [comment]
![cluster](https://cloud.githubusercontent.com/assets/15648392/12363213/e1260e16-bbc7-11e5-9351-6d6d31f903e3.jpg)
Zanimalo bi me tudi, kako bi se dalo s pomočjo podatkov v tabeli podatki3_2014, kjer sta podatka o dolgovih in deficitih narediti nekaj takega, kar prilagam v spodnji datoteki. Rad bi, da bi bile države sortirane po podobnosti glede en parameter, ki bi bil funkcija dolga in deficita kot npr. 

z=Dolg-10*Deficit

Torej države bi bile razdeljene v skupine na podlagi tega parametra.

**Comment by jaanos** [comment]
Če hočeš podatke razvrščati glede na en sam paramter, potem enostavno narediš razpredelnico z enim samim stolpcem, ki predstavlja ta parameter (normiranje potem ni potrebno). Sicer pa je poanta razvrščanja ravno ta, da ti ni treba sam določati kriterija, po katerem razvrščaš, ampak to zate stori algoritem (je pa res, da predpostavka, da so vse spremenljivke enako pomembne, ne drži vedno).

Kar si priložil, je dendrogram, ki pride iz hierarhičnega razvrščanja (letos na vajah tega nismo delali; ne vem, če ste na predavanjih povedali kaj o tem). Hierarhični model v R zgradiš s funkcijo `hclust`, dendrogram pa potem narišeš s `plot` (lahko pa uporabiš tudi paket ggdendro, ki omogoča risanje dendrogramov s pomočjo ggplot2). Tukaj število skupin ni vnaprej določeno, pač pa ga lahko določiš naknadno - poglej si funkciji `cutree` in `rect.hclust`.

**Comment by aleksandrov2** [comment]
Pozdravljeni, imam problem z zemljevidi v mapi analiza.r in sicer zem3 prikazuje evropske države razporejene v 2 skupini, da se grafično vidi zadnje čase tako velikokrat izrečeno besedo polarizacija evrope na sever in jug in zem4 prikazuje razporeditev evrope na 5 različnih skupin držav. Problem je, da mi noče narisati zemljevida zem4 in tudi ko zaženem project.Rmd mi reče, da sploh ne more narisati zemljevida zem3 in zem4?
Prav tako me zanima kako bi se dalo fiksirati barve, npr pri zem3, da bi severne države bile vedno označene z modro in južne vedno z rdečo, ne pa da je tako kot sedaj, ko je to stvar naključja?
Kako bi se dalo poleg legende kjer je sedaj zraven barve označena samo številka, napisati sever zraven modre in jug zraven rdeče barve?

**Comment by jaanos** [comment]
Ali imaš zadnjo verzijo naloženo na GitHubu? V `analiza.r` se namreč v trenutni verziji (cfb8e6a3) v vrsticah 29 in 30 sklicuješ na `k`, ki pa je definiran šele v vrsticah 33 oziroma 35. Če to poženem v smiselnem vrstnem redu, mi potem `zem3` izriše.

Pri drugem zemljevidu je problem ta, da v razpredelnici `skupina2` nimaš istoimenskega stolpca, pač pa bo treba v zemljevid skopirati stolpec `skupina`:

``` R
svet$skupina2 <- skupina2$skupina[m4]
```

Da fiksiraš barve, lahko ročno narediš lestvico, pri čemer določiš barve glede na predstavnika posamezne skupine. Hkrati lahko določiš še imena v legendi. Če hočeš fiksirati vrstni red, pred tem narediš še ustrezen urejen faktor, npr.

``` R
sever.jug <- skupina[c("SWE", "GRC"), "skupina"]
svet$skupina <- factor(skupina$skupina[m3], levels = sever.jug, ordered = TRUE)
evropa <- pretvori.zemljevid(svet, svet$continent == "Europe")
zem3 <- ggplot() + geom_polygon(data = evropa, aes(x=long, y=lat, 
                                group = group, fill = skupina),
                                color = "grey") + xlim(-10, 50) + 
  ylim(34, 72) + xlab("") + ylab("") +
  scale_fill_manual(values = setNames(c("#00bfc4", "#f8766d"), sever.jug),
                    labels = setNames(c("Sever", "Jug"), sever.jug),
                    na.value = "#7f7f7f")
```
