### ISSUE TITLE
Predikcija

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#7]
Naredil sem grafa deseti_graf in enajsti_graf, kjer sem prikazal države kot točke, kjer njena koordinata pove dolg in deficit države. Podatke sem aproksimiral s premico, potem pa sem se odločil, da bi me zanimal eksakten izračun npr. za državo z dolgom 0%,  25%, 50%, ..., 250% kolikšen bi bil njen deficit po predikciji. Za oba grafa s podatki leta 2006 in 2014 sem napisal takole.

napoved <- lm(data = podatki3 %>% filter(Cas == 2006), Deficit ~ Dolg)
predict(napoved, data.frame(Dolg=seq(0, 250, 25))) 

napoved2 <- lm(data = podatki3 %>% filter(Cas == 2014), Deficit ~ Dolg)
predict(napoved2, data.frame(Dolg=seq(0, 250, 25)))

Kako bi iz naredil npr. iz napoved2 naredil tabelo, ki bi imela stolpca Zadolženost, ki bi šla od 0% do 250% s korakom 25% in drugi stolpec Deficit, ki bi kazal deficit. Nekaj sem že poskušal narediti v mapi analiza.r

**Comment by jaanos** [comment]
Najlažje bo kar tako:

``` R
napoved.tabela <- data.frame(Dolg=seq(0, 250, 25))
napoved.tabela$Deficit <- predict(napoved, napoved.tabela) 
```

Razpredelnico `napoved.tabela` lahko uporabiš tudi pri drugih modelih, kjer napoveduješ iz stolpca `Dolg` - važno je samo, da ima podana razpredelnica stolpec z istim imenom.
