### ISSUE TITLE
Problem z grafom

### ISSUE THREAD

**Issue by aleksandrov2** [aleksandrov2/APPR-2015-16#9]
Problem imam, da  v datoteki project.Rmd sem v poglavju Analiza in vizualoizacija naajprej napisal kratek odstavek besedila, potem sem dal ukaz plot za 2 grafa in potem spet nekaj besedila.
Vendar pa ko dam knit pdf mi odpre najprej malo besedila, potem 1. graf in potem sploh ne nariše grafa 2. 
Skratka grafa nista na svojem mestu, zakaj?

**Comment by jaanos** [comment]
Drugi graf ni takoj za besedilom, ker na strani zanj ni dovolj prostora. Lahko sicer poskrbiš, da gre drugi graf na novo stran, tako da pred njega vstaviš prelom strani (`\newpage`). Sicer pa svetujem, da se raje v besedilu sklicuješ na grafe (npr. `\ref{fig:graf1}`, kjer je `graf1` oznaka bloka kode, kjer rišeš graf), kot pa da se zanašaš na vrstni red njihovega prikaza.
